"""Render a supplementary license-behaviour panel for the Scientific Data draft.

The panel is generated from REPO_LICENSE_DISTRIBUTION.csv and clusters detected
repository licenses by behavioural family. It is descriptive: it visualizes the
licensing signals used in the release-governance discussion, but it does not
replace the row-level release metadata generated by the export pipeline.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from matplotlib import font_manager
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Patch, Rectangle


HERE = Path(__file__).resolve().parent
SOURCE = HERE / "REPO_LICENSE_DISTRIBUTION.csv"
FIGURES = HERE / "figures"
FIGURES_CALIBRI = HERE / "figures_calibri"
BEHAVIOR_CSV = HERE / "LICENSE_BEHAVIOR_DISTRIBUTION.csv"
RELEASE_VIEW_CSV = HERE / "LICENSE_BEHAVIOR_RELEASE_VIEW_DISTRIBUTION.csv"


FAMILY_ORDER = [
    "no public licence detected",
    "permissive / low-obligation",
    "weak file/library reciprocity",
    "strong or network reciprocity",
    "attribution/content",
]

FAMILY_COLORS = {
    "no public licence detected": "#6B6F76",
    "permissive / low-obligation": "#2F7F68",
    "weak file/library reciprocity": "#C4872E",
    "strong or network reciprocity": "#7D4C8D",
    "attribution/content": "#3F6FA8",
}

BEHAVIOR_MAP = {
    "<missing>": "no public licence detected",
    "MIT": "permissive / low-obligation",
    "Apache-2.0": "permissive / low-obligation",
    "BSD-3-Clause": "permissive / low-obligation",
    "BSD-2-Clause": "permissive / low-obligation",
    "BSD-3-Clause-Clear": "permissive / low-obligation",
    "CC0-1.0": "permissive / low-obligation",
    "Unlicense": "permissive / low-obligation",
    "MulanPSL-2.0": "permissive / low-obligation",
    "MPL-2.0": "weak file/library reciprocity",
    "LGPL-3.0": "weak file/library reciprocity",
    "LGPL-2.1": "weak file/library reciprocity",
    "EUPL-1.2": "weak file/library reciprocity",
    "EPL-2.0": "weak file/library reciprocity",
    "GPL-3.0": "strong or network reciprocity",
    "GPL-2.0": "strong or network reciprocity",
    "AGPL-3.0": "strong or network reciprocity",
    "CC-BY-SA-4.0": "strong or network reciprocity",
    "CC-BY-4.0": "attribution/content",
}

NOTICE_LICENSES = {
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause-Clear",
    "MulanPSL-2.0",
    "MPL-2.0",
    "LGPL-3.0",
    "LGPL-2.1",
    "EUPL-1.2",
    "EPL-2.0",
    "GPL-3.0",
    "GPL-2.0",
    "AGPL-3.0",
    "CC-BY-SA-4.0",
    "CC-BY-4.0",
}

PATENT_NOTICE_LICENSES = {"Apache-2.0", "MPL-2.0", "EPL-2.0", "EUPL-1.2", "MulanPSL-2.0"}

LICENSE_DISPLAY_LABELS = {
    "<missing>": "No public licence detected",
}

FAMILY_DISPLAY_LABELS = {
    "no public licence detected": "no public licence detected",
    "permissive / low-obligation": "low-obligation",
    "weak file/library reciprocity": "weak reciprocity",
    "strong or network reciprocity": "strong/network reciprocity",
    "attribution/content": "attribution/content",
}


def choose_font(preferred: str) -> str:
    """Return a local font family if installed, otherwise use DejaVu Sans."""
    installed = {font.name for font in font_manager.fontManager.ttflist}
    if preferred in installed:
        return preferred
    if preferred == "Times New Roman" and "Times" in installed:
        return "Times"
    return "DejaVu Sans"


def format_count(value: float) -> str:
    return f"{int(round(value)):,}"


def format_pct(value: float, total: float) -> str:
    return f"{100 * value / total:.2f}%"


def format_pct_compact(value: float, total: float) -> str:
    pct = 100 * value / total
    if pct >= 0.1:
        return f"{pct:.2f}%"
    return f"{pct:.3f}%"


def display_license(value: str) -> str:
    return LICENSE_DISPLAY_LABELS.get(value, value)


def text_color_for_hex(color: str) -> str:
    color = color.lstrip("#")
    red, green, blue = (int(color[idx : idx + 2], 16) / 255 for idx in (0, 2, 4))
    luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    return "black" if luminance > 0.55 else "white"


def load_license_distribution() -> pd.DataFrame:
    df = pd.read_csv(SOURCE, keep_default_na=False)
    missing = sorted(set(df["repo_license"]) - set(BEHAVIOR_MAP))
    if missing:
        raise ValueError(f"Unmapped license identifiers: {missing}")

    df["behavior_family"] = df["repo_license"].map(BEHAVIOR_MAP)
    df["family_order"] = df["behavior_family"].map({value: idx for idx, value in enumerate(FAMILY_ORDER)})
    df["is_license_valid"] = df["license_category"].isin(["permissive", "copyleft", "other"])
    df["is_public_open"] = df["license_category"].eq("permissive")
    df["is_restricted"] = df["license_category"].eq("no_license")
    df["notice_or_attribution"] = df["repo_license"].isin(NOTICE_LICENSES)
    df["patent_notice"] = df["repo_license"].isin(PATENT_NOTICE_LICENSES)
    df["weak_reciprocity"] = df["behavior_family"].eq("weak file/library reciprocity")
    df["strong_or_network_reciprocity"] = df["behavior_family"].eq("strong or network reciprocity")
    df["internal_only"] = df["is_restricted"]
    df["display_license"] = df["repo_license"].map(display_license)

    return df.sort_values(["family_order", "rows"], ascending=[True, False]).reset_index(drop=True)


def write_tables(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    total = df["rows"].sum()

    behavior = (
        df.groupby("behavior_family", as_index=False)
        .agg(rows=("rows", "sum"), unique_repositories=("unique_repositories", "sum"))
        .assign(
            family_order=lambda data: data["behavior_family"].map(
                {value: idx for idx, value in enumerate(FAMILY_ORDER)}
            ),
            row_percent=lambda data: data["rows"] / total * 100,
        )
        .sort_values("family_order")
    )
    behavior[["behavior_family", "rows", "row_percent", "unique_repositories"]].to_csv(
        BEHAVIOR_CSV, index=False
    )

    view_rows = []
    views = [
        ("construction corpus", df.assign(view_rows=df["rows"])),
        ("license-valid rows", df.assign(view_rows=df["rows"].where(df["is_license_valid"], 0))),
        ("public-open rows", df.assign(view_rows=df["rows"].where(df["is_public_open"], 0))),
        ("restricted rows", df.assign(view_rows=df["rows"].where(df["is_restricted"], 0))),
    ]
    for view_name, view_df in views:
        view_total = int(view_df["view_rows"].sum())
        for family in FAMILY_ORDER:
            rows = int(view_df.loc[view_df["behavior_family"].eq(family), "view_rows"].sum())
            if rows:
                view_rows.append(
                    {
                        "release_view": view_name,
                        "behavior_family": family,
                        "rows": rows,
                        "view_percent": rows / view_total * 100 if view_total else 0,
                    }
                )
    release = pd.DataFrame(view_rows)
    release.to_csv(RELEASE_VIEW_CSV, index=False)
    return behavior, release


def draw_panel(df: pd.DataFrame, behavior: pd.DataFrame, release: pd.DataFrame, output_dir: Path, font: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    font_family = choose_font(font)

    plt.rcParams.update(
        {
            "font.family": font_family,
            "font.size": 9,
            "axes.titlesize": 10,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
        }
    )

    total = df["rows"].sum()
    fig = plt.figure(figsize=(13.2, 9.3), facecolor="white")
    gs = GridSpec(
        2,
        2,
        figure=fig,
        height_ratios=[1.15, 1.30],
        width_ratios=[0.96, 1.34],
        hspace=0.32,
        wspace=0.42,
    )

    ax_a = fig.add_subplot(gs[0, 0])
    ax_b = fig.add_subplot(gs[0, 1])
    ax_c = fig.add_subplot(gs[1, 0])
    ax_d = fig.add_subplot(gs[1, 1])

    # A. Behavioural family composition.
    behavior_sorted = behavior.sort_values("family_order")
    values = behavior_sorted["rows"].tolist()
    colors = [FAMILY_COLORS[item] for item in behavior_sorted["behavior_family"]]
    ax_a.pie(
        values,
        startangle=90,
        counterclock=False,
        colors=colors,
        labels=None,
        radius=1.10,
        center=(0.22, 0.0),
        wedgeprops={"width": 0.46, "edgecolor": "white", "linewidth": 1.0},
    )
    ax_a.text(0.22, 0.05, format_count(total), ha="center", va="center", fontsize=12, fontweight="bold")
    ax_a.text(0.22, -0.13, "instruction rows", ha="center", va="center", fontsize=8)
    ax_a.set_title("A. Behavioural families", loc="left", fontweight="bold", pad=6)
    legend_labels = [
        f"{FAMILY_DISPLAY_LABELS[row.behavior_family]}: {format_count(row.rows)} ({format_pct(row.rows, total)})"
        for row in behavior_sorted.itertuples()
    ]
    ax_a.legend(
        handles=[Patch(facecolor=color, label=label) for color, label in zip(colors, legend_labels)],
        frameon=False,
        loc="center right",
        bbox_to_anchor=(0.18, 0.5),
        handlelength=1.0,
        labelspacing=0.75,
    )
    ax_a.set_aspect("equal")
    ax_a.set_xlim(-1.55, 1.55)
    ax_a.set_ylim(-1.20, 1.20)

    # B. Exact license distribution.
    exact = df.sort_values("rows", ascending=True)
    y = range(len(exact))
    ax_b.barh(
        list(y),
        exact["rows"],
        color=[FAMILY_COLORS[item] for item in exact["behavior_family"]],
        edgecolor="white",
        linewidth=0.7,
        height=0.68,
    )
    ax_b.set_xscale("log")
    ax_b.set_yticks(list(y))
    ax_b.set_yticklabels(exact["display_license"])
    ax_b.set_xlabel("instruction rows, log scale")
    ax_b.set_title("B. Exact detected licences", loc="left", fontweight="bold", pad=7)
    ax_b.tick_params(axis="both", labelsize=8.8)
    ax_b.grid(axis="x", color="#E6E6E6", linewidth=0.8, which="both")
    ax_b.set_axisbelow(True)
    for idx, row in enumerate(exact.itertuples()):
        label = f"{format_count(row.rows)} ({format_pct_compact(row.rows, total)})"
        ax_b.text(row.rows * 1.08, idx, label, va="center", fontsize=8.2)
    ax_b.set_xlim(10, exact["rows"].max() * 2.2)
    ax_b.spines[["top", "right", "left"]].set_visible(False)

    # C. Licence-behaviour matrix.
    matrix_cols = [
        ("valid", "is_license_valid", "#2F7F68"),
        ("open", "is_public_open", "#74A892"),
        ("notice", "notice_or_attribution", "#3F6FA8"),
        ("patent", "patent_notice", "#62A6C4"),
        ("weak\nrecip.", "weak_reciprocity", "#C4872E"),
        ("strong\nrecip.", "strong_or_network_reciprocity", "#7D4C8D"),
        ("internal", "internal_only", "#6B6F76"),
    ]
    matrix_df = df.sort_values(["family_order", "rows"], ascending=[True, False]).reset_index(drop=True)
    ax_c.set_title("C. Behaviour and release signals", loc="left", fontweight="bold", pad=7)
    ax_c.set_xlim(-0.5, len(matrix_cols) - 0.5)
    ax_c.set_ylim(len(matrix_df) - 0.5, -0.5)
    ax_c.set_xticks(range(len(matrix_cols)))
    ax_c.set_xticklabels([item[0] for item in matrix_cols], rotation=0, ha="center")
    ax_c.set_yticks(range(len(matrix_df)))
    ax_c.set_yticklabels(matrix_df["display_license"])
    ax_c.tick_params(axis="both", length=0)

    for row_idx, row in enumerate(matrix_df.itertuples()):
        for col_idx, (_, col_name, color) in enumerate(matrix_cols):
            face = color if getattr(row, col_name) else "#F0F0F0"
            edge = "#FFFFFF" if getattr(row, col_name) else "#DDDDDD"
            ax_c.add_patch(
                Rectangle((col_idx - 0.39, row_idx - 0.39), 0.78, 0.78, facecolor=face, edgecolor=edge, linewidth=0.6)
            )
    for spine in ax_c.spines.values():
        spine.set_visible(False)

    # D. Release views by behavioural family.
    release_views = ["construction corpus", "license-valid rows", "public-open rows", "restricted rows"]
    release_pivot = (
        release.pivot_table(index="release_view", columns="behavior_family", values="rows", aggfunc="sum", fill_value=0)
        .reindex(release_views)
        .reindex(columns=FAMILY_ORDER, fill_value=0)
    )
    ax_d.set_title("D. Release-view composition", loc="left", fontweight="bold", pad=7)
    ax_d.set_xlim(-0.5, len(FAMILY_ORDER) + 0.85)
    ax_d.set_ylim(len(release_views) - 0.5, -0.5)
    ax_d.set_xticks(range(len(FAMILY_ORDER)))
    ax_d.set_xticklabels(
        [
            "no public\nlicence\ndetected",
            "low-\nobligation",
            "weak\nrecip.",
            "strong/network\nrecip.",
            "attribution/\ncontent",
        ],
        rotation=0,
        ha="center",
    )
    ax_d.set_yticks(range(len(release_views)))
    ax_d.set_yticklabels(release_views)
    ax_d.tick_params(axis="both", length=0)
    for row_idx, view_name in enumerate(release_views):
        row_total = release_pivot.loc[view_name].sum()
        for col_idx, family in enumerate(FAMILY_ORDER):
            value = int(release_pivot.loc[view_name, family])
            if value:
                face = FAMILY_COLORS[family]
                label = f"{format_count(value)}\n{value / row_total * 100:.1f}%"
                text_color = text_color_for_hex(face)
            else:
                face = "#F0F0F0"
                label = ""
                text_color = "#777777"
            ax_d.add_patch(
                Rectangle(
                    (col_idx - 0.45, row_idx - 0.37),
                    0.9,
                    0.74,
                    facecolor=face,
                    edgecolor="#FFFFFF" if value else "#DDDDDD",
                    linewidth=0.8,
                )
            )
            ax_d.text(col_idx, row_idx, label, ha="center", va="center", fontsize=7.3, color=text_color)
        ax_d.text(len(FAMILY_ORDER) + 0.05, row_idx, f"total\n{format_count(row_total)}", va="center", fontsize=8)
    for spine in ax_d.spines.values():
        spine.set_visible(False)

    bottom_handles = [
        Patch(facecolor=FAMILY_COLORS[family], label=FAMILY_DISPLAY_LABELS[family])
        for family in FAMILY_ORDER
    ]
    fig.legend(
        handles=bottom_handles,
        frameon=False,
        loc="lower center",
        bbox_to_anchor=(0.075, 0.005, 0.85, 0.055),
        ncol=5,
        mode="expand",
        columnspacing=1.9,
        handlelength=4.6,
        handleheight=1.9,
        borderaxespad=0,
        fontsize=9.6,
    )

    for suffix in ("svg", "png"):
        target = output_dir / f"suppfig_s6_license_behavior_panel.{suffix}"
        fig.savefig(target, dpi=450, bbox_inches="tight", pad_inches=0.035)
        print(f"saved {target}")
    plt.close(fig)


def main() -> None:
    df = load_license_distribution()
    behavior, release = write_tables(df)
    draw_panel(df, behavior, release, FIGURES, "Times New Roman")
    draw_panel(df, behavior, release, FIGURES_CALIBRI, "Calibri")
    print(f"saved {BEHAVIOR_CSV}")
    print(f"saved {RELEASE_VIEW_CSV}")


if __name__ == "__main__":
    main()
